### ISSUE TITLE
二代身份证正面签发机关与有效期识别能力

### ISSUE THREAD

**Issue by fuh** [Raymondhhh90/idcardocr#1]
您好，我想在代码基础上尝试了对身份证正面内容的识别，但是在生成模版的时候遇到Segmentation fault (core dumped)，请问您之前有遇到过这样的问题吗？

**Comment by Raymondhhh90** [comment]
能否详细描述一下出错信息

**Comment by hfuCN** [comment]
不好意思没及时回复，是cv2.UMat()方法出错了，好像是我opencv环境的问题，已经解决了，感谢。
