### ISSUE TITLE
经过测试发现【住址】字段三行情况下只能识别二行

### ISSUE THREAD

**Issue by xxzj990** [Raymondhhh90/idcardocr#14]
如题

**Comment by BIGPPWONG** [comment]
样本能提供下么

**Comment by xxzj990** [comment]
> 样本能提供下么

发到你邮箱了

**Comment by kenny-hash** [comment]
在 idcardocr.py 的825行
`        bottom_right = (top_left[0] + int(1700*x), top_left[1] + int(550*x))
`
改成
`        bottom_right = (top_left[0] + int(1700*x), top_left[1] + int(825*x))
`即可

**Comment by xxzj990** [comment]
> 在 idcardocr.py 的825行
> ` bottom_right = (top_left[0] + int(1700*x), top_left[1] + int(550*x))`
> 改成
> ` bottom_right = (top_left[0] + int(1700*x), top_left[1] + int(825*x))`即可

谢谢你的回复，感动~
